name: Close Stale Pull Requests

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes #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

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check and close stale pull requests
        id: close-prs
        uses: actions/github-script@v5
        with:
          github-token: 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
          script: |
            const test = context.github;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const pulls = await test.pulls.list({owner, repo});
            const now = new Date();
            const threshold = new Date(now.getTime() - 5 * 60000); // 5 minutes ago

            for (const pull of pulls.data) {
              const updated_at = new Date(pull.updated_at);
              if (updated_at < threshold) {
                await test.pulls.update({
                  owner,
                  repo,
                  pull_number: pull.number,
                  state: 'closed'
                });
              }
            }
