name: Close Stale Pull Requests

on:
  workflow_dispatch
  # schedule:
  #   - cron: '*/5 * * * *'  # Run every 5 minutes #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

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: 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
          stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
          stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
