name: Close Stale Pull Requests

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes #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

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.CLOSE_TOKEN }}
          stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
          stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
