name: Close Stale Pull Requests

on:
  workflow_dispatch
  
jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: treiff/draft-pr-closer@v0.2-alpha
        with:
          repo-token: ${{github.token}}
          days-before-close: 0
          stale-pr-message: 'This pull request has been marked as stale and closed because it has been inactive for more than 14 days'
          stale-pr-label: stale
